#
# The following strings will replace any blacklisted word from that category
#
CategoryUnknown: ["****"]
CategoryBodyContent: ["casserole", "lasagna"]
CategoryBodyPart: ["shoulder", "knee", "elbow"]
CategoryLocation: ["a warm place", "elsewhere"]
CategoryOffensive: ["yahoo", "I need to count to 10"]
CategoryProfession: ["astronaut", "dentist", "surgeon"]
CategoryRacist: ["dragon", "unicorn", "magic creature"]
CategorySexualNoun: ["chair", "pigeon"]
CategorySexualVerb: ["run", "walk", "look at"]
CategoryDerogative: ["citizen", "member", "person"]

eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 3

messages:

  #
  # Parameters: <new word>(%s)
  #
  DuplicateProfanity: "You specified the word \"%s\", but that word has already been blacklisted."

  #
  # Parameters: <new word>(%s), <existing word>(%s)
  #
  ProbablyDuplicateProfanity: "You specified the word \"%s\", but that word collides with existing profanity \"%s\"."

  #
  # Parameters: <new word>(%s)
  #
  ProfanityAdded: "Profanity \"%s\" has been added to the blacklist."
  