eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 2

#
# How tough should we be at stopping profanity?
#
# A word is always decoded from leet speak. If the word is in the whitelist, it will never be stopped.
#
# 0 = Don't stop anything
# 1 = Stop when spelled exactly as blacklisted word
# 2 = Stop when subpart of word is listed in ProfanityBuildingBlocks
# 3 = Stop when similar to blacklisted word
#
ProfanityLevel: 2

#
# Words that are not allowed as part of a word. If they are part of a word, the entire word is considered blacklisted
#
ProfanityBuildingBlocks: [fuck, dick]

#
# Should we log all messages for players considered to be offenders?
#
# 0 = NO
# 1 = YES
#
LogOffenderMessages: 1

#
# When a player has entered a profanity, this is how long time he/she is considered an "offender".
# A player is only considered an offender if a word he/she has written is stopped according to ProfanityLevel.
#
ProfanityOffenderCooldownTimeSpan: 1h

#
# When a player has entered a profanity, this is how long time he/she is considered a recent "offender".
# Recent offender messages will be logged over this time span to see if they try to circumvent the blacklist system.
# This does not take into account the ProfanityLevel. This means that if you are an offender, then you will continue to be
# considered a recent offender if you use similar words to blacklisted words any time while you are an offender.
#
ProfanityRecentOffenderCooldownTimeSpan: 20s

#
# Should we save a file with all words that are similar to blacklisted words?
#
# 0 = NO
# 1 = YES
#
SaveSimilar: 1

#
# Should we mark the words that replaces a profanity?
#
# 0 = NO
# 1 = YES
#
MarkReplacement: 1
MarkReplacementPrefix: "'"
MarkReplacementPostfix: "'"

#
# Should we mark the words that are similar to profanities?
#
# 0 = NO
# 1 = YES
#
MarkSimilar: 0
MarkSimilarPrefix: "<"
MarkSimilarPostfix: ">"

#
# The following strings will replace any blacklisted word from that category
#
CategoryUnknown: ["****"]
#CategoryBodyContent: ["casserole", "lasagna"]
#CategoryBodyPart: ["shoulder", "knee", "elbow"]
#CategoryLocation: ["a warm place", "elsewhere"]
#CategoryOffensive: ["yahoo", "I need to count to 10"]
#CategoryProfession: ["astronaut", "dentist", "surgeon"]
#CategoryRacist: ["dragon", "unicorn", "magic creature"]
#CategorySexualNoun: ["chair", "pigeon"]
#CategorySexualVerb: ["run", "walk", "look at"]
#CategoryDerogative: ["citizen", "member", "person"]

spam:
  #
  # If a chat line consists of more than this number of upper case letters, then the entire line will be converted into lower case
  #
  MaxNumberOfUpperCaseLettersInLine: 15
  
  #
  # If a chat line consists of more than this number of upper case words, then the entire line will be converted into lower case
  #
  MaxNumberOfUpperCaseWordsInLine: 3
  
  #
  # If a chat line is this similar to a newly entered line by the same player, it is considered a duplicate and will not be accepted.
  #
  LineIsProbablyDuplicate: 0.9
  
  #
  # The time that we will keep old lines to check for duplicates
  #
  TimeSpanToRememberLines: 30s
  
  #
  # The time that we will keep old lines to check for duplicates
  #
  MaxNumberOfRepeatedLines: 3
  
  #
  # The time that we have a restriction on the number of chats produced by a single player
  #
  ChatCoolDownTimeSpan: 30s
  
  #
  # The maximum number of produced chats by a single player during the ChatCoolDownTimeSpan
  #
  ChatCoolDownAllowedTimes: 10

mute:
  #
  # The time that a player will be muted by tempmute if no time is specified in the command
  #
  DefaultTempMuteTimeSpan: 60s
  
  #
  # The reason for the tempmute if not specified in the command
  #
  DefaultTempMuteReason: Unspecified
  
  #
  # All commands that are muted.
  #
  MutedCommands: ["me"]

commands:

  mute:

  #
  # Parameters: <player name>(%s), <number of seconds>(%d), <reason>(%s)
  #
  TempMutePlayer: "tempmute %s %ds %s"

  #
  # Parameters: <player name>(%s)
  #
  UnmutePlayer: "unmute %s"
    

messages:

  #
  # Parameters: <new word>(%s)
  #
  DuplicateProfanity: "The word \"%s\" has already been blacklisted."

  #
  # Parameters: <new word>(%s)
  #
  ProfanityNotFound: "The word \"%s\" was not blacklisted."

  #
  # Parameters: <new word>(%s)
  #
  ProfanityNotFoundButSimilarFound: "The word \"%s\" is not blacklisted. Did you mean \"%s\"?"

  #
  # Parameters: <new word>(%s), <existing word>(%s)
  #
  ProbablyDuplicateProfanity: "You specified the word \"%s\", please note that it is similar to the existing blacklisted word \"%s\"."

  #
  # Parameters: <new word>(%s)
  #
  ProfanityAdded: "The word \"%s\" has been added to the blacklist."

  #
  # Parameters: <word>(%s)
  #
  ProfanityRemoved: "The word \"%s\" has been removed from the blacklist."

  #
  # Parameters: <new word>(%s)
  #
  AcceptedWordWasNotBlacklisted: "The word \"%s\" is not blacklisted, so it will not be added as whitelisted."

  #
  # Parameters: <new word>(%s), <blacklisted word>(%s)
  #
  AcceptedWordAdded: "The word \"%s\" is now whitelisted, to prevent it from being mixed up with the blacklisted word \"%s\"."

  #
  # Parameters: <new word>(%s)
  #
  AcceptedWordNotFound: "The word \"%s\" was not whitelisted."

  #
  # Parameters: <word>(%s)
  #
  AcceptedWordRemoved: "The word \"%s\" is no longer whitelisted."

  #
  # Parameters: <new word>(%s)
  #
  AcceptedWordWasBlacklisted: "You can't whitelist \"%s\" because it is blacklisted with that spelling."

  #
  # Parameters: <new word>(%s)
  #
  DuplicateAcceptedWord: "The word \"%s\" has already been whitelisted."

  #
  # Parameters: <minimum length>(%d)
  #
  BlackListWordMinimalLength: "A word that should be blacklisted must have at least %d characters."

  #
  # Parameters: <player name>(%s), blacklisted word(%s), <exact phrasing>(%s)
  #
  NotifyAboutProfanity: "Player %s used the word \"%s\" (%s) which is blacklisted."

  #
  # Parameters: <player name>(%s), <similar word>(%s), <exact phrasing>(%s), <blacklisted word>(%s)
  #
  NotifyAboutSimilar: "Player %s used the word \"%s\" (%s), that is similar to the blacklisted word \"%s\"."

  #
  # Parameters: <player name>(%s), <composed word>(%s), <exact phrasing>(%s), <blacklisted word>(%s)
  #
  NotifyAboutComposed: "Player %s used the word \"%s\" (%s), that contains the blacklisted building block \"%s\"."
  
  spam:
    #
    # Parameters: <number of messages>(%d), <seconds>(%d)
    #
    ChattingTooFast: "The chat intensity is limited per player, maximum is %d messages per %d seconds."
    
    #
    # Parameters: -
    #
    ChatDuplicateMessage: "You are not allowed to repeat the same message many times."

  
  mute:
    #
    # Parameters: <player name>(%s), <time>(%s), <reason>(%s)
    #
    TempMutedPlayer: "Player %s has been muted %s with reason \"%s\"."
    
    #
    # Parameters: <player name>(%s)
    #
    UnmutedPlayer: "Player %s has been unmuted."

  doc:
     TempMuteCommand: "/tempmute <player> [<time>] [<reason>]"
     UnmuteCommand: "/unmute <player>"
