name: EithonCop
main: net.eithon.plugin.cop.Plugin
version: 0.3
author: vanbrayne
depend: [EithonLibrary]
description: A Minecraft plugin
commands:
  eithoncop:
    description: Police activities
    usage: /eithoncop blacklist | whitelist
    permission-message: You don't have <permission>
permissions:
  eithoncop.*:
    description: Gives access to all eithoncop commands
    default: op
    eithoncop.blacklist: true
    eithoncop.whitelist: true
  eithoncop.blacklist:
    description: Access to /eithoncop blacklist command
    default: op
  eithoncop.whitelist:
    description: Access to /eithoncop whitelist command
    default: op
    
