name: EithonCop
main: net.eithon.plugin.cop.Plugin
version: ${project.version}
author: vanbrayne
depend: [EithonLibrary, Herochat]
description: A Minecraft plugin
commands:
  eithoncop:
    description: Police activities
    usage: /eithoncop blacklist | whitelist | tempmute | unmute | freeze
    permission-message: You don't have <permission>
permissions:
  eithoncop.*:
    description: Gives access to all eithoncop commands
    default: op
    eithoncop.blacklist: true
    eithoncop.whitelist: true
    eithoncop.tempmute: true
    eithoncop.unmute: true
    eithoncop.notify-about-profanity: true
    eithoncop.notify-about-similar: true
    eithoncop.spam.has-no-cool-down: true
    eithoncop.spam.can-repeat-messages: true
    eithoncop.freeze.on : true
    eithoncop.freeze.off : true
    eithoncop.freeze.restore : true
    eithoncop.freeze.list : true
  eithoncop.blacklist:
    description: Access to /eithoncop blacklist commands
    default: op
  eithoncop.whitelist:
    description: Access to /eithoncop whitelist commands
    default: op
  eithoncop.tempmute:
    description: Access to /eithoncop tempmute commands
    default: op
  eithoncop.unmute:
    description: Access to /eithoncop unmute commands
    default: op
  eithoncop.freeze.on:
    description: Access to /eithoncop freeze on command
    default: op
  eithoncop.freeze.off:
    description: Access to /eithoncop freeze off command
    default: op
  eithoncop.freeze.restore:
    description: Access to /eithoncop freeze restore command
    default: op
  eithoncop.freeze.list:
    description: Access to /eithoncop freeze list command
    default: op
  eithoncop.notify-about-profanity:
    description: Get notified when someone uses a blacklisted word
    default: op
  eithoncop.notify-about-similar:
    description: Get notified when someone uses a word similar to a blacklisted word
    default: op
  eithoncop.spam.has-no-cool-down:
    description: The chat cool down rules are not applied if a player has this permission
    default: op
  eithoncop.spam.can-repeat-messages:
    description: The spam repeat rules are not applied if a player has this permission
    default: op

