name: EithonCop
main: net.eithon.plugin.cop.Plugin
version: 0.11
author: vanbrayne
depend: [EithonLibrary]
description: A Minecraft plugin
commands:
  eithoncop:
    description: Police activities
    usage: /eithoncop blacklist | whitelist | tempmute | unmute
    permission-message: You don't have <permission>
permissions:
  eithoncop.*:
    description: Gives access to all eithoncop commands
    default: op
    eithoncop.blacklist: true
    eithoncop.whitelist: true
    eithoncop.tempmute: true
    eithoncop.unmute: true
    eithoncop.notify-about-profanity: true
    eithoncop.notify-about-similar: true
  eithoncop.blacklist:
    description: Access to /eithoncop blacklist commands
    default: op
  eithoncop.whitelist:
    description: Access to /eithoncop whitelist commands
    default: op
  eithoncop.tempmute:
    description: Access to /eithoncop tempmute commands
    default: op
  eithoncop.unmute:
    description: Access to /eithoncop unmute commands
    default: op
  eithoncop.notify-about-profanity:
    description: Get notified when someone uses a blacklisted word
    default: op
  eithoncop.notify-about-similar:
    description: Get notified when someone uses a word similar to a blacklisted word
    default: op
